### ISSUE TITLE
please rename entry points to start with 'lammps.'

### ISSUE THREAD

**Issue by ltalirz** [aiidaplugins/aiida-lammps#11]
your plugin currently exposes a number of entry points that don't follow the convention to start with the name of the package.
See the travis logs of the aiida registry:
https://travis-ci.org/aiidateam/aiida-registry/jobs/591463873#L342-L347

please consider renaming them to start with 'lammps.'

**Comment by ltalirz** [comment]
+ add the "Framework::AiiDA" classifier to the setup.json

**Comment by JPchico** [comment]
I think all the entry points already start with `lammps` is there anything else that needs to be changed @chrisjsewell ?

**Comment by ltalirz** [comment]
Hey @JPchico , see here
https://github.com/aiidaplugins/aiida-lammps/blob/8f618541784bbd6360efc653350570cf76398e83/setup.json#L46-L56

**Comment by chrisjsewell** [comment]
Yeh it was only `dynaphopy` and that has been removed

**Comment by ltalirz** [comment]
https://github.com/aiidaplugins/aiida-lammps/blob/e7186d7f7abb169c62366a61ce74ce306a50d860/pyproject.toml#L77-L81

**Comment by JPchico** [comment]
@ltalirz those potential types are going to be deprecated in the refactoring that we are doing, instead a single `"lammps.lammps_potential" = "aiida_lammps.data.lammps_potential:LammpsPotentialData"` will remain to take care of all the different potential types in a more general manner.

**Comment by chrisjsewell** [comment]
Yep but that is a lammps specific entry point group @ltalirz, not to do with aiida (I.e.there is no risk of clashes)

**Comment by ltalirz** [comment]
Oh I see - in that case all good!
