### ISSUE TITLE
setup requirements hardcode aiida-core version

### ISSUE THREAD

**Issue by ltalirz** [aiidaplugins/aiida-lammps#12]
The current setup requirements pin the aiida-core version:
https://github.com/abelcarreras/aiida-lammps/blob/8660201047984c8a28efbffaadb2b71c86ba19fc/setup.json#L10

Please replace this with something like `aiida-core>=1.0.0b3`

**Comment by yakutovicha** [comment]
Wanted to create the same issue, but it is already here.  Thanks @ltalirz

**Comment by chrisjsewell** [comment]
I'll fix this eventually in #13
