### ISSUE TITLE
Transfer to aiidaplugins?

### ISSUE THREAD

**Issue by chrisjsewell** [aiidaplugins/aiida-lammps#14]
Hey @abelcarreras I have just created https://github.com/aiidaplugins as a central option for people to host their aiida plugin repositories, and invited you as a member.
Would you be willing to transfer this repository to there? (naturally you would still be given administrator access)

**Comment by abelcarreras** [comment]
Sure, no problem!
Can you do it by yourself or I should do it?

**Comment by abelcarreras** [comment]
done

**Comment by chrisjsewell** [comment]
thanks 😄
