### ISSUE TITLE
Examples and README out of date

### ISSUE THREAD

**Issue by JPchico** [aiidaplugins/aiida-lammps#18]
I was trying the lammps plugin after the syncing to make it compatible to AiiDA 1.4 and I noticed that the examples and `README.md` are out of date. Namely they refer to the need to pass the structure when defining the `lammps.potential`, this seems to have been removed in 71fa4c4509788d610154d2eb8f052f79f791a887

I can make a PR and fix these issues if that is okay.

**Comment by chrisjsewell** [comment]
sounds good to me thanks 😄

**Comment by JPchico** [comment]
@chrisjsewell The examples and the `README.md` are all updated. I only did not update the `launch_lammps_combinate.py`
The potential is passed as `inputs.potential = Dict(dict=potential)` I do not know if this is due to some difference on how the potential is treated in this particular workchain in comparison with the others.

**Comment by chrisjsewell** [comment]
Brilliant cheers I'll try and have a look ASAP. Yeh the combinate stuff was not written by me and I've never used it, so you probably know as well as me lol

**Comment by JPchico** [comment]
Fixed via #19 .
