### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by JPchico** [aiidaplugins/aiida-lammps#25]
The plugin right now has no documentation. A simple documentation should be made and possibly deployed to readthedocs so that users can easily start using the plugin.

**Comment by chrisjsewell** [comment]
If there's one thing I know its documentation lol (I'm also lead developer on https://myst-parser.readthedocs.io) I'll add some documentation in the next day or two 👍

**Comment by JPchico** [comment]
No worries @chrisjsewell ! I was planning to do it myself (I just cannot assign myself in the issue xD) So I'll be making a PR with some documentation during the coming week. Of course, the docstrings are pretty bare right now, so the API documentation will probably need several revisions. Something I do not have, and I've never done is to actually deploy the documentation to something like readthedocs, so that is something I would appreciate the help with :)

**Comment by chrisjsewell** [comment]
Well do you want me to just make the documentation “structure” then you can add more of the writing?

**Comment by JPchico** [comment]
Sure thing @chrisjsewell ! I was planning to use a template similar to either aiida-core or aiida-quantumespresso. I have deployed them before in our internal gitlab server, just never done it in readthedocs, but you are the expert so feel free of putting a "structure" and I can fill it in :)

**Comment by chrisjsewell** [comment]
done: https://aiida-lammps.readthedocs.io
I haven't bothered to add the API documentation yet, will do that another time

**Comment by chrisjsewell** [comment]
obviously let me know/open an issue if there is anyway you would like to change how it looks etc 😄

**Comment by JPchico** [comment]
Fantastic! Thank you @chrisjsewell I'll fill the documentation up, it looks great!
