### ISSUE TITLE
 minimize.energy_tolerance: 0

### ISSUE THREAD

**Issue by nim-hrkn** [aiidaplugins/aiida-lammps#49]
LAMMPS accepts minimize.energy_tolerance = 0.
Ref. https://docs.lammps.org/minimize.html,
but aiida-lammps doesn't.  How about accepting it also in aiida-lammps if possible? 
Excuse me that I can't follow the code and I'm not sure whether it is supported or not in the 'devel' branch. Is it better to write in 'Discussions' page?

**Comment by JPchico** [comment]
Hi @nim-hrkn!
Sorry for the very late reply. We have been working into refactoring the code so that these kind of issues cannot happen anymore. Feel free to look at the development version of the code, in there you can setup the energy tolerance to whatever value you choose.

**Comment by JPchico** [comment]
@nim-hrkn This is now possible in the latest release if you have any more problems feel free to open the issue again.
