### ISSUE TITLE
Handling of the restarfile

### ISSUE THREAD

**Issue by JPchico** [aiidaplugins/aiida-lammps#58]
Right now by default the binary restart file is written at the end of the simulation and uploaded to the database. This is of course not ideal, as the file can be quite large and it might not be necessary in a large variety of cases.

Also this does not help with possible restarts if the calculation fails before the last step is reached, e.g. by reaching the walltime.

To try to solve this issue, a couple of parameters can be added, one whether the restart will be printed or not, and how often it should be printed (this so that it is printed during the simulation).

If these files are chosen to be uploaded then whichever if found to be last, either the one at the end of the simulation, or the last one that is printed before the simulation fails, is taken and stored as a `SinglefileData`

The possibility to instead use a `RemoteData` node will be given, where one can instead pass this folder and use the restartfile present there (probably by making a symbolic link to the calculation folder) to run the restart.

What do you think @chrisjsewell ?

**Comment by chrisjsewell** [comment]
yeo sounds great thanks 👍

**Comment by JPchico** [comment]
Closed via 004c746
