### ISSUE TITLE
Removal of deprecated features

### ISSUE THREAD

**Issue by JPchico** [aiidaplugins/aiida-lammps#63]
Looking at the changes being done to aiida-lammps right now we have two parsers, several potential types and calculations. All of them are basically redundant by the new `BaseLammpsCalculation` and `LammpsPotential`types.

I think that we probably should remove them to make sure that the code is more streamlined and easy to maintain. 

The idea was to keep them for backwards compatibility, but in principle for any new calculation one can use the new functions.

Perhaps one can give a way of importing old calculations using a immigrant function that uses the clever `input_script` input from @sphuber

I'm all for cleaning this up and keeping only one parser, one calculation and one potential structure. The rest of the specific cases can be treated by custom workchains.

What do you think @chrisjsewell ?

**Comment by chrisjsewell** [comment]
> All of them are basically redundant by the new BaseLammpsCalculation and LammpsPotentialtypes.

yeh I'd be happy for you to deprecate them 👍 

perhaps you could add some documentation, if its not there already, on how you can now run the old calculations using the new infrastructure

**Comment by JPchico** [comment]
That seems fine by me.
I have examples on how to run some of them, but I'll make sure that there are examples for all of them and then I'll remove them
