### ISSUE TITLE
:recycle:  Add warnings and errors to the parsing

### ISSUE THREAD

**Issue by JPchico** [aiidaplugins/aiida-lammps#83]
Right now the parsing of the lammps output is done via the log file. However, the logfile does not include all the information, as errors and warnings are often not found there. Instead one should use the redirected output from the screen. This output should have all the information of the log file plus the errors and warnings. 

The warnings are good to be able to detected minor recoverable problems, and the error is good to be able to detect when and why lammps itself fails.

**Comment by JPchico** [comment]
A question @sphuber, the log files that are in the test for the raw parser, are they log files or out files? They look like out files (as I can see some warnings in them).

I'm basically wondering if I can use them for the tests of the "out" file, in principle it should be the same thing as the info of the log file is the same info of the out file minus some parts. but I just want to double check.

**Comment by sphuber** [comment]
> I'm basically wondering if I can use them for the tests of the "out" file, in principle it should be the same thing as the info of the log file is the same info of the out file minus some parts. but I just want to double check.

I guess you can remove the log files (if they are there) and if the tests pass, it is all good

**Comment by JPchico** [comment]
Sure I'm just wondering since those were the files that you added, and I'm unsure if they are logs or outs. I'm like 75% sure they are outs, and then a simple git mv solves all the issues

**Comment by JPchico** [comment]
Closed via #84
